// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    gas_service
    (
        init => init
        upgrade => upgrade
        payGasForContractCall => pay_gas_for_contract_call
        payNativeGasForContractCall => pay_native_gas_for_contract_call
        payGasForExpressCall => pay_gas_for_express_call
        payNativeGasForExpressCall => pay_native_gas_for_express_call
        addGas => add_gas
        addNativeGas => add_native_gas
        addExpressGas => add_express_gas
        addNativeExpressGas => add_native_express_gas
        collectFees => collect_fees
        refund => refund
        setGasCollector => set_gas_collector
        gas_collector => gas_collector
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
