[package]
name = "interchain-token-service-proxy"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "0.50.3"

[dev-dependencies.dharitri-sc-scenario]
version = "0.50.3"
