// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    ping_ping_interchain
    (
        init => init
        upgrade => upgrade
        execute => execute
        executeWithInterchainToken => execute_with_interchain_token
        ping => ping
        pong => pong
        pongAll => pong_all
        setInterchainTokenService => set_interchain_token_service
        getUserAddresses => get_user_addresses
        getInterchainTokenService => interchain_token_service
        getPingAmount => ping_amount
        getDeadline => deadline
        getActivationTimestamp => activation_timestamp
        getMaxFunds => max_funds
        getUserStatus => user_status
        pongAllLastUser => pong_all_last_user
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
