network: 'mainnet'
metaChainShardId: 4294967295
api:
  public: true
  publicPort: 3001
  private: true
  privatePort: 4001
  websocket: true
cron:
  cacheWarmer: true
  fastWarm: false
  queueWorker: true
  elasticUpdater: false
flags:
  useRequestCaching: true
  useKeepAliveAgent: true
  useTracing: false
  useRequestLogging: false
  useVmQueryTracing: false
  processNfts: true
  collectionPropertiesFromGateway: false
features:
  eventsNotifier:
    enabled: false
    port: 5674
    url: 'amqp://guest:guest@127.0.0.1:5672'
    exchange: 'all_events'
    queue: 'api-process-logs-and-events'
  guestCaching:
    enabled: false
    hitsThreshold: 100
    ttl: 12
  transactionPool:
    enabled: false
  transactionPoolWarmer:
    enabled: false
    cronExpression: '*/5 * * * * *'
    ttlInSeconds: 60 
  updateCollectionExtraDetails:
    enabled: false
  updateAccountExtraDetails:
    enabled: false
    transfersLast24hUrl: 'https://tools.dharitri.org/growth-api/explorer/widgets/most-used/applications'
  marketplace:
    enabled: false
    serviceUrl: 'https://nfts-graph.dharitri.org/graphql'
  exchange:
    enabled: false
    serviceUrl: 'https://graph.xexchange.com/graphql'
  dataApi:
    enabled: false
    serviceUrl: 'https://data-api.dharitri.org'
  auth:
    enabled: false
    maxExpirySeconds: 86400
    acceptedOrigins:
      - ''
    admins:
      - ''
    jwtSecret: ''
  stakingV4:
    enabled: false
    cronExpression: '*/5 * * * * *'
    activationEpoch: 1391
  chainAndromeda:
    enabled: true
    activationEpoch: 1763
  nodeEpochsLeft:
    enabled: false
  transactionProcessor:
    enabled: false
    maxLookBehind: 1000
  transactionCompleted:
    enabled: false
    maxLookBehind: 1000
    logLevel: 'Error'
  transactionBatch:
    enabled: false
    maxLookBehind: 1000
  deepHistory:
    enabled: false
    url: ''
  elasticCircuitBreaker:
    enabled: false
    durationThresholdMs: 5000
    failureCountThreshold: 5
    resetTimeoutMs: 30000
  statusChecker:
    enabled: false
    thresholds:
      tokens: 1000
      nodes: 5000
      providers: 150
      tokenSupplyCount: 100
      tokenAssets: 100
      tokenAccounts: 1000
      tokenTransactions: 1000
      nodeValidators: 3260
  nftScamInfo:
    enabled: false
  processNfts:
    enabled: false
    nftQueueName: 'api-process-nfts'
    deadLetterQueueName: 'api-process-nfts-dlq'
  tps:
    enabled: false
    maxLookBehindNonces: 100
  nodesFetch:
    enabled: true
    serviceUrl: 'https://api.dharitri.org'
  tokensFetch:
    enabled: true
    serviceUrl: 'https://api.dharitri.org'
  providersFetch:
    enabled: true
    serviceUrl: 'https://api.dharitri.org'
  assetsFetch:
    enabled: true
    assetesUrl: 'https://tools.dharitri.org/assets-cdn'
image:
  width: 600
  height: 600
  type: 'png'
aws:
  s3KeyId: ''
  s3Secret: ''
  s3Bucket: 'media.dharitri.org'
  s3Region: ''
urls:
  self: 'https://api.dharitri.org'
  elastic:
    - 'https://index.dharitri.org'
  gateway:
    - 'https://gateway.dharitri.org'
  verifier: 'https://play-api.dharitri.org'
  redis: '127.0.0.1'
  rabbitmq: 'amqp://127.0.0.1:5672'
  providers: 'https://delegation-api.dharitri.org/providers'
  delegation: 'https://delegation-api.dharitri.org'
  media: 'https://media.dharitri.org'
  tmp: '/tmp'
  ipfs: 'https://ipfs.io/ipfs'
  socket: 'socket-api-fra.dharitri.org'
  maiarId: 'https://id-api.dharitri.org'
indexer:
  type: 'elastic'
  maxPagination: 10000
database:
  enabled: false
  url: 'mongodb://127.0.0.1:27017/api?authSource=admin'
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  database: 'api'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 50
  cacheDuration: 3
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  dcdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt'
  metabonding: 'erd1qqqqqqqqqqqqqpgq50dge6rrpcra4tp9hl57jl0893a4r2r72jpsk39rjj'
inflation:
  - 1952123
  - 1746637
  - 1541150
  - 1335663
  - 1130177
  - 924690
  - 719203
nftProcess:
  parallelism: 1
  maxRetries: 3
