[package]
name = "governance"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "0.50.3"

[dependencies.gateway]
path = "../gateway"
